### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by abiring** [miykael/gif_your_nifti#7]
Hi ! 
hope you are fine . Can u help me in solving ths problem
```
gif_your_nifti '/home/abir/Bureau/data/training/patient028/patient028_4d.nii'
Traceback (most recent call last):
  File "/usr/local/bin/gif_your_nifti", line 11, in <module>
    load_entry_point('gif-your-nifti==0.2.0', 'console_scripts', 'gif_your_nifti')()
  File "/home/abir/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/abir/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/abir/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/abir/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/gif_your_nifti/__main__.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/gif_your_nifti/core.py", line 4, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nibabel-3.1.0-py2.7.egg/nibabel/__init__.py", line 40, in <module>
    from . import analyze as ana
  File "/usr/local/lib/python2.7/dist-packages/nibabel-3.1.0-py2.7.egg/nibabel/analyze.py", line 935
    def from_file_map(klass, file_map, *, mmap=True, keep_file_open=None):
                                        ^
SyntaxError: invalid syntax
```

**Comment by ofgulban** [comment]
Hi @abiring , thanks for the error report. I see that you are using Python2.7. Can you try it with Python3 environment? Python 2.7 is not supported anymore so maybe some of our dependencies are causing trouble because of this.

**Comment by abiring** [comment]
hello yes it's work thanks . I 'm working  on MRI cardiac  is it possible to modify the axis of representation of MRI so that it is clearer ?

**Comment by ofgulban** [comment]
Good to hear that it works! I think the best way to go about modifying the axes is to reorient the image beforehand (e.g. using nibabel). We did not implement such functionality in our command line interface. I was thinking about implementing this this but it will probably happen sometime later in the year.

**Comment by abiring** [comment]
oky thank u so much
